### ISSUE TITLE
[To-Do] Relocate Shopping Districts

### ISSUE THREAD

**Issue by aisukuma** [Stardust-Labs-MC/StardustMC#54]
### Username

kuma

### Describe the issue

For the switch over to GriefDefender's AdvancedRegionMarket exclusive version soon, relocate shopping districts to another area. Require manual schematic backups to shop plots.

- [x] Relocate Flipside/Flopside District
  - Schematic Backup Progress: 100%
- [x] Relocate Nether District
  - Schematic Backup Progress: 100%
  - Relocate to Nether
- [x] Relocate End District
  - Schematic Backup Progress: 100%
  - Relocate to End
- [x] Relocate Deep Dark District
  - Schematic Backup Progress: 100%

**Comment by aisukuma** [comment]
Schematic backups completed. Reworking new district areas now.
